# Generated by Django 5.2.8 on 2026-01-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.ImageField(upload_to='home/')),
                ('primary_button_text', models.CharField(default='Explore DevOps', max_length=50)),
                ('primary_button_link', models.CharField(default='/devops/', max_length=200)),
                ('secondary_button_text', models.CharField(default='Read Blogs', max_length=50)),
                ('secondary_button_link', models.CharField(default='/blogs/', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeBanner',
        ),
    ]
